### ISSUE TITLE
CaseInsensitive containers do not work with pprint

### ISSUE THREAD

**Issue by sseraj** [mdolab/baseclasses#53]
## Description
The `CaseInsensitive` containers are not properly formatted when printed with `pprint`. This bug was introduced with the ABC implementation in #51. I realized this because the ADflow options dictionary is now printed in one massive line instead of having line breaks. The same bug applies to both `CaseInsensitiveDict` and `CaseInsensitiveSet`.

### Steps to reproduce issue
Here is a MWE for `CaseInsensitiveDict`:

```
from baseclasses.utils import CaseInsensitiveDict
from pprint import pprint

sensitive = {"b-longstring": 2, "a-longstring": 1, "c-longstring": 3, "e-longstring": 5, "d-longstring": 4}
insensitive = CaseInsensitiveDict(sensitive)

pprint(sensitive)
pprint(insensitive)
```

### Current behavior
```
>>> pprint(sensitive)
{'a-longstring': 1,
 'b-longstring': 2,
 'c-longstring': 3,
 'd-longstring': 4,
 'e-longstring': 5}

>>> pprint(insensitive)
{'b-longstring': 2, 'a-longstring': 1, 'c-longstring': 3, 'e-longstring': 5, 'd-longstring': 4}
```

### Expected behavior
```
>>> pprint(sensitive)
{'a-longstring': 1,
 'b-longstring': 2,
 'c-longstring': 3,
 'd-longstring': 4,
 'e-longstring': 5}

>>> pprint(insensitive)
{'a-longstring': 1,
 'b-longstring': 2,
 'c-longstring': 3,
 'd-longstring': 4,
 'e-longstring': 5}
```

**Comment by nwu63** [comment]
So it seems that `pprint`'s implementation uses `isinstance(obj, dict)` to call class-specific formatters, see [here](https://github.com/python/cpython/blob/3.8/Lib/pprint.py#L179). Unfortunately because we do not subclass `dict` but its parent class, we don't get the benefit for `pprint`. That's a bummer.

At the same time, despite implementing the (correct) `__repr__` function, it does not seem straightforward to get `pprint` to just call that. It uses some dispatch thing which I don't fully understand. I guess we have a few options here:
1. subclass `pprint` as recommended [here](https://stackoverflow.com/questions/40828173/how-can-i-make-my-class-pretty-printable-in-python)
2. write a custom print function and use that when printing insensitive dicts
3. make `__repr__` return a nicely formatted string similar to `pprint`, and use `print` instead

I am leaning slightly towards 3, since `pprint` is really only meant to work for built in Python objects. If we can figure out when we are calling `pprint` on dicts vs. insensitive dicts (static type checking!) then we can just reliably call `print` instead.
